// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.
// source: hello.soy

/**
 * @fileoverview Templates in namespace test.
 * @public
 */

goog.provide('test');

goog.require('goog.soy');
goog.require('soy');
goog.require('soy.asserts');
goog.require('soydata.VERY_UNSAFE');


/**
 * @param {!test.helloName.Params} opt_data
 * @param {(?goog.soy.IjData|?Object<string, *>)=} opt_ijData
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
test.helloName = function(opt_data, opt_ijData) {
  opt_ijData = /** @type {!goog.soy.IjData} */ (opt_ijData);
  /** @type {string} */
  const name = soy.asserts.assertType(typeof opt_data.name === 'string', 'name', opt_data.name, 'string');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('Hello ' + soy.$$escapeHtml(name) + '!');
};
/**
 * @typedef {{
 *  name: string,
 * }}
 */
test.helloName.Params;
if (goog.DEBUG) {
  /** @type {string} */
  test.helloName.soyTemplateName = 'test.helloName';
}
